### ISSUE TITLE
"images" needs chmod 777

### ISSUE THREAD

**Issue by Silex** [kristophjunge/docker-mediawiki#10]
Uploads don't work if `/images` is not chmod 777.

Also the `/data` folder looks useless, what is it used for?

**Comment by kristophjunge** [comment]
**Image Folder**
At some point i moved the images directory to `/images` and created a symlink to `/var/www/mediawiki/images`. The reason for this was better convenience when mounting directories into the container since `/images` is shorter. Also the real location of the images folder inside the container can be changed without breaking existing setups.

The ownership for the `images` directory was intended to be set to the `www-data` user but only the code was there to set the ownership of the symlink. I fixed that and it works now.

**Data Folder**
The data folder is used to store SQLite data when using SQLite as database. You can ignore it when using a different database type.

**Comment by Silex** [comment]
:+1:
