### ISSUE TITLE
Container doesnt start

### ISSUE THREAD

**Issue by wernermarcel** [kristophjunge/docker-mediawiki#12]
In the logs i see : 

[emerg] 12#12: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

**Comment by wernermarcel** [comment]
ipv6 is disabled on the host..

**Comment by kristophjunge** [comment]
Hello please retry with the latest version. Note that the port exposed by the container was changed to 8080.

If your problem is related to IPv6, please try the following:

Create your own nginx.conf. Start with the one from inside the container:

`docker exec -it mediawiki_wiki cat /etc/nginx/nginx.conf`

In your nginx.conf file remove the following line:

`listen [::]:8080;`

Mount your own nginx.conf file into the container:

`-v /var/mediawiki/nginx.conf:/etc/nginx/nginx.conf `
